import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
test('PostgreSQL migration, tenant isolation, permissions, uniqueness and audit integrity',async()=>{
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;`);
 await db.exec(await readFile(new URL('../supabase/migrations/001_ecod.sql',import.meta.url),'utf8'));
 const admin='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002',viewer='00000000-0000-4000-8000-000000000003';
 const w1='00000000-0000-4000-8000-000000000011',w2='00000000-0000-4000-8000-000000000012';
 const c1='00000000-0000-4000-8000-000000000021',c2='00000000-0000-4000-8000-000000000022',d1='00000000-0000-4000-8000-000000000031';
 await db.exec(`insert into auth.users values('${admin}','admin@example.com'),('${other}','other@example.com'),('${viewer}','viewer@example.com');insert into public.workspaces(id,name) values('${w1}','A'),('${w2}','B');insert into public.memberships values('${admin}','${w1}','admin'),('${other}','${w2}','recruiter'),('${viewer}','${w1}','viewer');`);
 const act=async(user)=>db.exec(`reset role;select set_config('request.jwt.claim.sub','${user}',false);set role authenticated;`);
 await act(admin);
 await db.exec(`insert into candidates(id,name,email,company) values('${c1}','Test Person','person@example.com','Old employer');`);
 assert.equal((await db.query('select count(*)::int as count from history')).rows[0].count,1);
 await db.exec(`update candidates set company='New employer' where id='${c1}';`);
 assert.equal((await db.query(`select snapshot->>'company' as company from history where action='Profile updated'`)).rows[0].company,'Old employer');
 await assert.rejects(()=>db.exec(`insert into candidates(name,email) values('Duplicate','PERSON@EXAMPLE.COM');`),/unique|duplicate/i);
 await assert.rejects(()=>db.exec(`update memberships set role='admin';`),/permission/i);
 await assert.rejects(()=>db.exec(`delete from history;`),/permission/i);
 await db.exec(`insert into demands(id,title,client,skills,"minExperience","maxNotice",budget,location,mode,positions,priority,target,weights) values('${d1}','Engineer','Example',array['Python'],3,30,30,'Pune','Remote',1,'High',current_date,'{"skills":35,"experience":20,"readiness":20,"availability":10,"budget":10,"location":5}');`);
 await db.exec(`insert into considerations("candidateId","demandId",stage) values('${c1}','${d1}','Identified');`);
 await assert.rejects(()=>db.exec(`insert into considerations("candidateId","demandId",stage) values('${c1}','${d1}','Contacted');`),/unique|duplicate/i);
 await act(other);
 assert.equal((await db.query('select count(*)::int as count from candidates')).rows[0].count,0);
 assert.equal((await db.query('select count(*)::int as count from history')).rows[0].count,0);
 await db.exec(`insert into candidates(id,name,email) values('${c2}','Other Person','other@example.com');`);
 await assert.rejects(()=>db.exec(`insert into considerations("candidateId","demandId",stage) values('${c2}','${d1}','Identified');`),/foreign key/i);
 await assert.rejects(()=>db.exec(`insert into candidates(workspace_id,name,email) values('${w1}','Intruder','intruder@example.com');`),/row-level security/i);
 await act(viewer);
 assert.equal((await db.query('select count(*)::int as count from candidates')).rows[0].count,1);
 await assert.rejects(()=>db.exec(`insert into candidates(name,email) values('Blocked','blocked@example.com');`),/row-level security/i);
 const result=await db.query(`update candidates set company='Attempted edit' where id='${c1}' returning id`);
 assert.equal(result.rows.length,0);
 await db.exec('reset role;set role anon;');
 await assert.rejects(()=>db.exec('select * from candidates;'),/permission/i);
 await db.close();
});
