import test, { afterEach } from 'node:test';
import assert from 'node:assert/strict';
import { load, mount, screen, click, fireEvent, act, cleanup, stopVite } from './ui-harness.js';
afterEach(cleanup);
test.after(stopVite);
test('mobile navigation contains focus, closes with Escape and restores scrolling and trigger focus', async () => {
  localStorage.clear();
  const { default: App } = await load('/src/App.jsx');
  await mount(App, {});
  const trigger = screen.getByRole('button', { name: 'Open navigation' });
  document.body.style.overflow = 'auto';
  await click(trigger);
  assert.equal(trigger.getAttribute('aria-expanded'), 'true');
  assert.equal(document.body.style.overflow, 'hidden');
  const aside = document.getElementById('workspace-navigation');
  assert.ok(aside.contains(document.activeElement));
  const items = [...aside.querySelectorAll('button:not(:disabled),a[href]')];
  items.at(-1).focus();
  await act(async () => fireEvent.keyDown(document, { key: 'Tab' }));
  assert.equal(document.activeElement, items[0]);
  await act(async () => fireEvent.keyDown(document, { key: 'Tab', shiftKey: true }));
  assert.equal(document.activeElement, items.at(-1));
  await act(async () => fireEvent.keyDown(document, { key: 'Escape' }));
  assert.equal(trigger.getAttribute('aria-expanded'), 'false');
  assert.equal(document.body.style.overflow, 'auto');
  assert.equal(document.activeElement, trigger);
  await click(trigger);
  await click(screen.getByRole('button', { name: 'Close navigation' }));
  assert.equal(trigger.getAttribute('aria-expanded'), 'false');
  assert.equal(document.body.style.overflow, 'auto');
  await click(trigger);
  await click(screen.getByRole('button', { name: 'Open your account from sidebar' }));
  assert.equal(trigger.getAttribute('aria-expanded'), 'false');
  assert.ok(screen.getByRole('dialog'));
  await click(screen.getByRole('button', { name: 'Close dialog' }));
  assert.equal(document.body.style.overflow, 'auto');
});
