-- Replace the public email-only status lookup with a per-application secret code. The code is
-- generated by PostgreSQL and returned only by the corresponding application RPC response.
begin;

alter table public."publicApplications"
  add column if not exists "statusToken" uuid not null default gen_random_uuid();
create unique index if not exists public_apps_status_token_unique
  on public."publicApplications"("statusToken");

-- The previous email-only function allowed anyone who knew an address to inspect application
-- status. Drop it rather than leaving a callable compatibility overload.
drop function if exists public.api_public_application_status(uuid, text);
create or replace function public.api_public_application_status(
  p_workspace uuid,
  p_email text,
  p_status_token uuid
)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(jsonb_agg(jsonb_build_object(
    'ref', left(a.id::text, 8),
    'role', coalesce(d.title, 'General application'),
    'location', d.location,
    'status', a.status,
    'submittedOn', to_char(a.created, 'YYYY-MM-DD')
  ) order by a.created desc), '[]'::jsonb)
  from public."publicApplications" a
  left join public.demands d on d.workspace_id = a.workspace_id and d.id = a."demandId"
  where p_workspace is not null
    and a.workspace_id = p_workspace
    and p_email is not null
    and p_status_token is not null
    and lower(btrim(p_email)) = lower(btrim(a.email))
    and a."statusToken" = p_status_token;
$$;
revoke all on function public.api_public_application_status(uuid, text, uuid) from public;
grant execute on function public.api_public_application_status(uuid, text, uuid) to anon, authenticated;

-- The apply RPC returns a separate high-entropy code; the application id itself is not used as
-- a public status credential. Existing direct callers must adopt the JSON response shape.
drop function if exists public.api_public_apply(uuid, jsonb);
create or replace function public.api_public_apply(ws uuid, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  app_id uuid;
  role_id uuid;
  status_token uuid;
begin
  if payload is null
     or coalesce(trim(payload->>'name'), '') = ''
     or coalesce(trim(payload->>'email'), '') = '' then
    raise exception 'name and email are required';
  end if;
  if payload->>'email' !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
    raise exception 'enter a valid email address';
  end if;
  if not coalesce((payload->>'consentContact')::boolean, false) then
    raise exception 'consent to contact is required';
  end if;

  if not exists (select 1 from public.workspaces w where w.id = ws) then
    raise exception 'unknown workspace';
  end if;

  begin
    role_id := nullif(payload->>'demandId', '')::uuid;
  exception when invalid_text_representation then
    raise exception 'select an open role';
  end;
  if role_id is null then
    raise exception 'select an open role';
  end if;
  if not exists (
    select 1
    from public.demands d
    where d.id = role_id
      and d.workspace_id = ws
      and d.status = 'Open'
      and d."careersVisible" is true
  ) then
    raise exception 'role is no longer accepting applications';
  end if;

  insert into public."publicApplications"(
    workspace_id, "demandId", name, email, phone, linkedin, message,
    "consentContact", "consentSharing"
  )
  values (
    ws, role_id, trim(payload->>'name'), lower(trim(payload->>'email')),
    coalesce(trim(payload->>'phone'), ''), coalesce(trim(payload->>'linkedin'), ''),
    coalesce(payload->>'message', ''), true,
    coalesce((payload->>'consentSharing')::boolean, false)
  )
  returning id, "statusToken" into app_id, status_token;

  return jsonb_build_object('applicationId', app_id, 'statusToken', status_token);
end;
$$;
revoke all on function public.api_public_apply(uuid, jsonb) from public;
grant execute on function public.api_public_apply(uuid, jsonb) to anon, authenticated;

commit;
