begin;
create schema if not exists ecod_comms_private;
revoke all on schema ecod_comms_private from public,anon,authenticated;
grant usage on schema ecod_comms_private to authenticated;
do $$begin if exists(select 1 from pg_roles where rolname='service_role')then grant usage on schema ecod_comms_private to service_role;end if;end$$;
create table if not exists ecod_comms_private.policy(workspace_id uuid primary key references public.workspaces(id),enabled boolean not null default false,outcome text not null default 'success' check(outcome in('success','transient','permanent')),daily_limit integer not null default 3 check(daily_limit between 1 and 20),actor uuid,updated_at timestamptz not null default clock_timestamp());
create table if not exists ecod_comms_private.templates(id uuid primary key,workspace_id uuid not null references public.workspaces(id),key text not null,version integer not null,body jsonb not null,actor uuid not null,at timestamptz not null default clock_timestamp(),unique(workspace_id,key,version));
create table if not exists ecod_comms_private.preferences(id uuid primary key,workspace_id uuid not null,candidate_id uuid not null,purpose text not null,body jsonb not null,actor uuid not null,at timestamptz not null default clock_timestamp(),sequence bigint generated always as identity,foreign key(workspace_id,candidate_id)references public.candidates(workspace_id,id));
create table if not exists ecod_comms_private.intents(id uuid primary key,workspace_id uuid not null,candidate_id uuid not null,template_id uuid not null references ecod_comms_private.templates(id),context jsonb not null,source_head text not null,preview jsonb not null,actor uuid not null,status text not null default 'Queued' check(status in('Queued','Retrying','Test recorded','Suppressed','Cancelled','Failed')),reason text not null default '',attempts integer not null default 0,available_at timestamptz not null,expires_at timestamptz not null,created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default clock_timestamp(),foreign key(workspace_id,candidate_id)references public.candidates(workspace_id,id));
create unique index if not exists comms_pending_unique on ecod_comms_private.intents(workspace_id,candidate_id,template_id,source_head)where status in('Queued','Retrying');
create index if not exists comms_due on ecod_comms_private.intents(available_at,id)where status in('Queued','Retrying');
create index if not exists comms_candidate on ecod_comms_private.intents(workspace_id,candidate_id,created_at desc,id);
create table if not exists ecod_comms_private.attempts(id uuid primary key default gen_random_uuid(),workspace_id uuid not null,candidate_id uuid not null,intent_id uuid not null references ecod_comms_private.intents(id),attempt integer not null,outcome text not null,checksum text not null,at timestamptz not null default clock_timestamp(),unique(intent_id,attempt),foreign key(workspace_id,candidate_id)references public.candidates(workspace_id,id));
create table if not exists ecod_comms_private.receipts(workspace_id uuid not null,actor uuid not null,id uuid not null,candidate_id uuid,request jsonb not null,result jsonb not null,at timestamptz not null default clock_timestamp(),primary key(workspace_id,actor,id));
create table if not exists ecod_comms_private.health(singleton boolean primary key default true check(singleton),at timestamptz not null);
do $$declare n text;begin foreach n in array array['policy','templates','preferences','intents','attempts','receipts','health']loop execute format('alter table ecod_comms_private.%I enable row level security',n);execute format('revoke all on ecod_comms_private.%I from public,anon,authenticated',n);end loop;end$$;

create or replace function ecod_comms_private.source(ws uuid,c uuid,t uuid,p_context jsonb)returns jsonb language plpgsql volatile security invoker set search_path=''as $$
declare person public.candidates;tpl ecod_comms_private.templates;contact ecod_contacts_private.contacts;pref jsonb;consent jsonb;demand jsonb;interview jsonb;reason text:='';result jsonb;vars jsonb;subject text;body text;k text;begin
 select *into person from public.candidates where workspace_id=ws and id=c;if not found then raise exception 'Candidate unavailable';end if;
 select *into tpl from ecod_comms_private.templates where workspace_id=ws and id=t;if not found then raise exception 'Template unavailable';end if;
 if jsonb_typeof(p_context)is distinct from'object'or exists(select 1 from jsonb_object_keys(p_context)x(key_name)where key_name<>all(array['demand','interview']))then raise exception 'Only scoped demand and interview context is supported';end if;
 if nullif(p_context->>'demand','')is not null then select jsonb_build_object('id',id,'title',title,'status',status)into demand from public.demands where workspace_id=ws and id=(p_context->>'demand')::uuid;if demand is null then raise exception 'Demand unavailable';end if;end if;
 if nullif(p_context->>'interview','')is not null then select jsonb_build_object('id',id,'scheduledAt',"scheduledAt",'status',status,'demandId',"demandId")into interview from public.interviews where workspace_id=ws and id=(p_context->>'interview')::uuid and "candidateId"=c;if interview is null or(interview->>'demandId')::uuid is distinct from(demand->>'id')::uuid then raise exception 'Interview must belong to this candidate and demand';end if;end if;
 select *into contact from ecod_contacts_private.contacts where workspace_id=ws and candidate_id=c and kind='email'and active and verified_at between clock_timestamp()-interval'365 days'and clock_timestamp()order by preferred desc,verified_at desc,id limit 1;
 select to_jsonb(x)into consent from public.consents x where workspace_id=ws and "candidateId"=c and purpose=tpl.body->>'purpose'order by date desc,(status<>'granted')desc,id desc limit 1;
 select p.body into pref from ecod_comms_private.preferences p where workspace_id=ws and candidate_id=any(ecod_access_private.identity_family(ws,c)) and purpose=tpl.body->>'purpose'order by sequence desc limit 1;
 if person."mergedInto"is not null then reason:='Retired identity';elsif person."processingRestricted"or person.status='Unavailable'then reason:='Outbound recruiting hold or unavailable';elsif tpl.body->'enabled'<>'true'::jsonb or exists(select 1 from ecod_comms_private.templates newer where newer.workspace_id=ws and newer.key=tpl.key and newer.version>tpl.version)then reason:='Template disabled or obsolete';elsif contact.id is null then reason:='No current confirmed email contact';elsif consent->>'status'is distinct from'granted'or(consent->>'date')::timestamptz>clock_timestamp()then reason:='Current purpose consent not granted';elsif pref->'optOut'='true'::jsonb then reason:='Purpose email preference opted out';elsif tpl.body->>'kind'in('interview-invite','interview-reminder')and(interview is null or interview->>'status'is distinct from'Scheduled'or(interview->>'scheduledAt')::timestamptz<=clock_timestamp())then reason:='A future active interview is required';elsif tpl.body->>'kind'='application-acknowledgement'and(demand is null or not exists(select 1 from public.considerations where workspace_id=ws and "candidateId"=c and "demandId"=(demand->>'id')::uuid))then reason:='A recorded candidate application is required';end if;
 vars:=jsonb_build_object('candidateName',person.name,'anthroId',person."anthroId",'demandTitle',coalesce(demand->>'title',''),'scheduledAt',coalesce(interview->>'scheduledAt',''));
 subject:=tpl.body->>'subject';body:=tpl.body->>'text';foreach k in array array['candidateName','anthroId','demandTitle','scheduledAt']loop
 if (strpos(subject||body,'{{'||k||'}}')>0)and coalesce(vars->>k,'')=''then reason:='Required template context is missing';end if;
 subject:=replace(subject,'{{'||k||'}}',coalesce(vars->>k,''));body:=replace(body,'{{'||k||'}}',coalesce(vars->>k,''));end loop;
 if length(subject)>200 or length(body)>12000 or subject~E'[\\r\\n]'then reason:='Rendered message exceeds text or single-line subject limits';subject:=left(subject,200);body:=left(body,12000);end if;
 result:=jsonb_build_object('template',to_jsonb(tpl),'candidate',jsonb_build_array(person.id,person.name,person."anthroId",person.status,person."processingRestricted",person."mergedInto"),'contact',to_jsonb(contact),'consent',consent,'preference',pref,'context',p_context,'demand',demand,'interview',interview);
 return jsonb_build_object('head',ecod_journey_private.token(ws,result),'eligible',reason='','reason',reason,'preference',coalesce(pref,jsonb_build_object('optOut',false,'startHour',0,'endHour',24)),'preview',jsonb_build_object('transport','test-only','recipient',contact.value,'contactId',contact.id,'candidate',person.name,'anthroId',person."anthroId",'subject',subject,'text',body,'purpose',tpl.body->>'purpose','templateVersion',tpl.version,'templateKey',tpl.key));
end$$;

create or replace function ecod_comms_private.api(p_action text,p_candidate uuid,p_operation uuid,p_head text,p_payload jsonb,p_offset integer)returns jsonb language plpgsql security definer set search_path=''as $$
declare ws uuid:=ecod_access_private.member_workspace(p_action not in('context','preview','browse'));r ecod_comms_private.receipts;req jsonb;result jsonb;rows jsonb;tpl ecod_comms_private.templates;intent ecod_comms_private.intents;data jsonb;policy ecod_comms_private.policy;k text;n integer;at timestamptz;begin
 if p_action is null or p_action not in('context','preview','browse','template','policy','preference','queue','cancel','retry')or p_offset is null or p_offset not between 0 and 1000000 or jsonb_typeof(p_payload)is distinct from'object'or octet_length(p_payload::text)>20000 then raise exception 'Invalid communication request';end if;
 if p_action not in('context','preview','browse')then perform 1 from public.workspaces where id=ws for update;end if;
 if p_candidate is not null then perform 1 from public.candidates where workspace_id=ws and id=p_candidate and "mergedInto"is null for update;if not found then raise exception 'Open an active candidate in your workspace';end if;end if;
 select *into policy from ecod_comms_private.policy where workspace_id=ws;
 if p_action='context'then
  if exists(select 1 from jsonb_object_keys(p_payload)x(key_name)where key_name<>'contextQuery')or(p_payload?'contextQuery'and(jsonb_typeof(p_payload->'contextQuery')is distinct from'string'or length(p_payload->>'contextQuery')>200))then raise exception 'Invalid context search';end if;
  select coalesce(jsonb_agg(to_jsonb(t)order by t.key),'[]')into rows from(select distinct on(key)*from ecod_comms_private.templates where workspace_id=ws order by key,version desc limit 101)t;if jsonb_array_length(rows)>100 then raise exception 'Template catalog limit exceeded';end if;
  result:=jsonb_build_object('transport','test-only','policyHead',ecod_journey_private.token(ws,coalesce(to_jsonb(policy),'null'::jsonb)),'policy',case when policy.workspace_id is null then jsonb_build_object('enabled',false,'outcome','success','daily_limit',3)else to_jsonb(policy)end,'templates',rows,'lastWorkerRun',(select h.at from ecod_comms_private.health h));
  select coalesce(jsonb_agg(case when p_candidate is null then jsonb_build_object('id',t.id,'candidate_id',t.candidate_id,'status',t.status,'reason',t.reason,'attempts',t.attempts,'created_at',t.created_at,'available_at',t.available_at,'expires_at',t.expires_at,'templateKey',t.preview->>'templateKey')else to_jsonb(t)||jsonb_build_object('receipts',(select coalesce(jsonb_agg(to_jsonb(a)order by attempt),'[]')from ecod_comms_private.attempts a where a.intent_id=t.id))end order by created_at desc,id),'[]')into rows from(select *from ecod_comms_private.intents where workspace_id=ws and(p_candidate is null or candidate_id=any(ecod_access_private.identity_family(ws,p_candidate)))order by created_at desc,id limit 26 offset p_offset)t;
  result:=result||jsonb_build_object('rows',case when jsonb_array_length(rows)>25 then rows-25 else rows end,'more',jsonb_array_length(rows)>25);
  if p_candidate is not null then result:=result||jsonb_build_object('preferences',coalesce((select jsonb_agg(to_jsonb(t))from(select distinct on(purpose)*from ecod_comms_private.preferences where workspace_id=ws and candidate_id=any(ecod_access_private.identity_family(ws,p_candidate)) order by purpose,sequence desc)t),'[]'),'demands',coalesce((select jsonb_agg(jsonb_build_object('id',id,'title',title))from(select *from public.demands where workspace_id=ws and(coalesce(p_payload->>'contextQuery','')=''or strpos(lower(title),lower(p_payload->>'contextQuery'))>0)order by id limit 100)t),'[]'),'interviews',coalesce((select jsonb_agg(jsonb_build_object('id',id,'demandId',"demandId",'scheduledAt',"scheduledAt",'status',status))from(select *from public.interviews iv where workspace_id=ws and "candidateId"=p_candidate and(coalesce(p_payload->>'contextQuery','')=''or exists(select 1 from public.demands d where d.workspace_id=ws and d.id=iv."demandId"and strpos(lower(d.title),lower(p_payload->>'contextQuery'))>0))order by "scheduledAt"desc limit 100)t),'[]'));insert into public."auditEvents"(workspace_id,"entityType","entityId",action,detail,actor)values(ws,'candidates',p_candidate,'server_read','Communication test history',auth.uid()::text);end if;return result;
 elsif p_action='browse'then
  if exists(select 1 from jsonb_object_keys(p_payload)x(key_name)where key_name<>all(array['query','status','tag']))or exists(select 1 from jsonb_each(p_payload)x where jsonb_typeof(x.value)<>'string'or length(x.value#>>'{}')>200)then raise exception 'Invalid communication segment';end if;
  select coalesce(jsonb_agg(to_jsonb(t)order by id),'[]')into rows from(select id,name,"anthroId",status from public.candidates where workspace_id=ws and "mergedInto"is null and not "processingRestricted"and(coalesce(p_payload->>'query','')=''or strpos(lower(name||' '||"anthroId"),lower(p_payload->>'query'))>0)and(coalesce(p_payload->>'status','')=''or status=p_payload->>'status')and(coalesce(p_payload->>'tag','')=''or p_payload->>'tag'=any(tags))order by id limit 26 offset p_offset)t;perform ecod_access_private.audit_candidate_reads(ws,rows,'Communication segment');return jsonb_build_object('rows',case when jsonb_array_length(rows)>25 then rows-25 else rows end,'more',jsonb_array_length(rows)>25);
 elsif p_action='preview'then
  if p_candidate is null or exists(select 1 from jsonb_object_keys(p_payload)x(key_name)where key_name<>all(array['template','context']))then raise exception 'Choose a candidate, template and scoped context';end if;return ecod_comms_private.source(ws,p_candidate,(p_payload->>'template')::uuid,coalesce(p_payload->'context','{}'));
 end if;
 if p_operation is null then raise exception 'Durable operation is required';end if;
 if p_action in('template','policy','retry')then if not public.is_admin()then raise exception 'Administrator required';end if;perform ecod_private.require_privileged_mfa(ws);end if;
 req:=jsonb_build_array(p_action,p_candidate,p_head,p_payload);
 select *into r from ecod_comms_private.receipts where workspace_id=ws and actor=auth.uid()and id=p_operation;if found then if r.request<>req then raise exception 'Communication operation conflict';end if;return r.result||jsonb_build_object('replayed',true);end if;
 if p_action='template'then
  if exists(select 1 from jsonb_object_keys(p_payload)x(key_name)where key_name<>all(array['key','version','kind','purpose','subject','text','enabled']))or jsonb_typeof(p_payload->'key')is distinct from'string'or coalesce(p_payload->>'key','')!~'^[a-z][a-z0-9_-]{0,39}$'or coalesce(p_payload->>'kind','')not in('application-acknowledgement','interview-invite','interview-reminder','freshness-check','redeployment','custom')or coalesce(p_payload->>'purpose','')not in('recruiting-contact','marketing')or jsonb_typeof(p_payload->'enabled')is distinct from'boolean'then raise exception 'Invalid template policy';end if;
  foreach k in array array['subject','text']loop if jsonb_typeof(p_payload->k)is distinct from'string'or length(btrim(p_payload->>k))not between 1 and(case when k='subject'then 200 else 8000 end)or(p_payload->>k)~'[<>]'or(k='subject'and(p_payload->>k)~E'[\\r\\n]')then raise exception 'Templates require bounded plain text and single-line subject';end if;
   data:=to_jsonb(regexp_replace(p_payload->>k,'\{\{(candidateName|anthroId|demandTitle|scheduledAt)\}\}','','g'));if (data#>>'{}')~'\{\{|\}\}'then raise exception 'Unknown or malformed template placeholder';end if;end loop;
  select *into tpl from ecod_comms_private.templates where workspace_id=ws and key=p_payload->>'key'order by version desc limit 1;
  if jsonb_typeof(p_payload->'version')is distinct from'number'or(p_payload->>'version')::numeric<>coalesce(tpl.version,0)then raise exception 'Template changed; review current version';end if;
  if tpl.id is null and(select count(distinct key)from ecod_comms_private.templates where workspace_id=ws)>=100 then raise exception 'Template catalog limit reached';end if;
  insert into ecod_comms_private.templates(id,workspace_id,key,version,body,actor)values(p_operation,ws,p_payload->>'key',coalesce(tpl.version,0)+1,p_payload-'key'-'version',auth.uid());result:=jsonb_build_object('templateId',p_operation,'version',coalesce(tpl.version,0)+1);
 elsif p_action='policy'then
  if p_head is distinct from ecod_journey_private.token(ws,coalesce(to_jsonb(policy),'null'::jsonb))then raise exception 'Test policy changed; refresh and review';end if;
  if exists(select 1 from jsonb_object_keys(p_payload)x(key_name)where key_name<>all(array['enabled','outcome','dailyLimit']))or jsonb_typeof(p_payload->'enabled')is distinct from'boolean'or coalesce(p_payload->>'outcome','')not in('success','transient','permanent')or jsonb_typeof(p_payload->'dailyLimit')is distinct from'number'or(p_payload->>'dailyLimit')::numeric not between 1 and 20 or(p_payload->>'dailyLimit')::numeric<>trunc((p_payload->>'dailyLimit')::numeric)then raise exception 'Invalid test policy';end if;
  insert into ecod_comms_private.policy(workspace_id,enabled,outcome,daily_limit,actor)values(ws,(p_payload->>'enabled')::boolean,p_payload->>'outcome',(p_payload->>'dailyLimit')::integer,auth.uid())on conflict(workspace_id)do update set enabled=excluded.enabled,outcome=excluded.outcome,daily_limit=excluded.daily_limit,actor=excluded.actor,updated_at=clock_timestamp();result:=jsonb_build_object('enabled',p_payload->'enabled','transport','test-only');
 elsif p_action='preference'then
  if p_candidate is null or exists(select 1 from jsonb_object_keys(p_payload)x(key_name)where key_name<>all(array['purpose','optOut','startHour','endHour','source']))or coalesce(p_payload->>'purpose','')not in('recruiting-contact','marketing')or jsonb_typeof(p_payload->'optOut')is distinct from'boolean'or jsonb_typeof(p_payload->'source')is distinct from'string'or length(btrim(p_payload->>'source'))not between 10 and 1000 then raise exception 'Record purpose preference with sourced evidence';end if;
  foreach k in array array['startHour','endHour']loop if jsonb_typeof(p_payload->k)is distinct from'number'or(p_payload->>k)::numeric<>trunc((p_payload->>k)::numeric)then raise exception 'Use integer UTC window hours';end if;end loop;
  if(p_payload->>'startHour')::integer not between 0 and 23 or(p_payload->>'endHour')::integer not between 1 and 24 or(p_payload->>'startHour')::integer>=(p_payload->>'endHour')::integer then raise exception 'Use a UTC window with start before end';end if;
  insert into ecod_comms_private.preferences(id,workspace_id,candidate_id,purpose,body,actor)values(p_operation,ws,p_candidate,p_payload->>'purpose',p_payload-'purpose',auth.uid());result:=jsonb_build_object('preferenceId',p_operation);
 elsif p_action='queue'then
  if p_candidate is null or exists(select 1 from jsonb_object_keys(p_payload)x(key_name)where key_name<>all(array['template','context','availableAt']))then raise exception 'Choose candidate and reviewed preview';end if;
  if policy.enabled is distinct from true then raise exception 'Test transport is paused';end if;
  data:=ecod_comms_private.source(ws,p_candidate,(p_payload->>'template')::uuid,coalesce(p_payload->'context','{}'));
  if data->>'head'is distinct from p_head then raise exception 'Preview source changed; refresh and review';end if;if data->'eligible'<>'true'::jsonb then raise exception 'Suppressed: %',data->>'reason';end if;
  if jsonb_typeof(p_payload->'availableAt')is distinct from'string'then raise exception 'Choose a scheduled timestamp';end if;at:=(p_payload->>'availableAt')::timestamptz;if at<clock_timestamp()-interval'5 minutes'or at>clock_timestamp()+interval'30 days'then raise exception 'Schedule within 30 days';end if;
  if exists(select 1 from ecod_comms_private.intents where workspace_id=ws and candidate_id=p_candidate and source_head=p_head and status in('Queued','Retrying','Test recorded')and created_at>clock_timestamp()-interval'24 hours')then raise exception 'Equivalent reviewed message already queued or test recorded';end if;
  if(select count(*)from ecod_comms_private.intents where workspace_id=ws and candidate_id=p_candidate and created_at>clock_timestamp()-interval'24 hours')>=20 then raise exception 'Candidate intent quota reached';end if;
  insert into ecod_comms_private.intents(id,workspace_id,candidate_id,template_id,context,source_head,preview,actor,available_at,expires_at)values(p_operation,ws,p_candidate,(p_payload->>'template')::uuid,coalesce(p_payload->'context','{}'),p_head,data->'preview',auth.uid(),greatest(at,clock_timestamp()),greatest(at,clock_timestamp())+interval'7 days');result:=jsonb_build_object('intentId',p_operation,'status','Queued','transport','test-only');
 else
  select *into intent from ecod_comms_private.intents where workspace_id=ws and candidate_id=p_candidate and id=(p_payload->>'intent')::uuid for update;if not found then raise exception 'Intent unavailable';end if;
  if exists(select 1 from jsonb_object_keys(p_payload)x(key_name)where key_name<>all(array['intent','reason']))or jsonb_typeof(p_payload->'reason')is distinct from'string'or length(btrim(p_payload->>'reason'))not between 10 and 1000 then raise exception 'Record a recovery reason';end if;
  if p_action='cancel'then if intent.status not in('Queued','Retrying','Failed')then raise exception 'Only pending or failed test intents can be cancelled';end if;update ecod_comms_private.intents set status='Cancelled',reason=p_payload->>'reason',updated_at=clock_timestamp()where id=intent.id;
  else
   if policy.enabled is distinct from true or intent.status<>'Failed'or intent.attempts>=6 or intent.expires_at<=clock_timestamp()then raise exception 'Unexpired failed intent and active test policy required; maximum six total attempts';end if;
   data:=ecod_comms_private.source(ws,p_candidate,intent.template_id,intent.context);if data->'eligible'<>'true'::jsonb or data->>'head'<>intent.source_head then raise exception 'Original reviewed source is no longer eligible; prepare a new intent';end if;
   update ecod_comms_private.intents set status='Retrying',available_at=clock_timestamp(),reason=p_payload->>'reason',updated_at=clock_timestamp()where id=intent.id;
  end if;result:=jsonb_build_object('intentId',intent.id,'action',p_action);
 end if;
 insert into ecod_comms_private.receipts(workspace_id,actor,id,candidate_id,request,result)values(ws,auth.uid(),p_operation,p_candidate,req,result);
 insert into public."auditEvents"(workspace_id,"entityType","entityId",action,detail,actor)values(ws,case when p_candidate is null then'workspaces'else'candidates'end,coalesce(p_candidate,ws),'comms_'||p_action,p_operation::text,auth.uid()::text);return result||jsonb_build_object('replayed',false);
end$$;

create or replace function ecod_comms_private.run(p_limit integer)returns jsonb language plpgsql security definer set search_path=''as $$
declare w record;c record;i ecod_comms_private.intents;policy ecod_comms_private.policy;data jsonb;n integer:=0;recorded integer:=0;suppressed integer:=0;failed integer:=0;hour integer;outcome text;begin
 if p_limit is null or p_limit not between 1 and 50 then raise exception 'Batch size must be 1 to 50';end if;
 insert into ecod_comms_private.health values(true,clock_timestamp())on conflict(singleton)do update set at=excluded.at;
 for w in select x.id from public.workspaces x where exists(select 1 from ecod_comms_private.policy p where p.workspace_id=x.id and p.enabled)and exists(select 1 from ecod_comms_private.intents m where m.workspace_id=x.id and m.status in('Queued','Retrying')and m.available_at<=clock_timestamp())order by x.id limit p_limit for share of x skip locked loop
 for c in select x.id,x.workspace_id from public.candidates x where x.workspace_id=w.id and exists(select 1 from ecod_comms_private.intents m where m.workspace_id=x.workspace_id and m.candidate_id=x.id and m.status in('Queued','Retrying')and m.available_at<=clock_timestamp())order by x.id limit p_limit for update of x skip locked loop
  perform 1 from public.workspaces where id=c.workspace_id for share;
  select *into policy from ecod_comms_private.policy where workspace_id=c.workspace_id;if policy.enabled is distinct from true then continue;end if;
  for i in select *from ecod_comms_private.intents where workspace_id=c.workspace_id and candidate_id=c.id and status in('Queued','Retrying')and available_at<=clock_timestamp()order by available_at,id for update skip locked loop
   exit when n>=p_limit;n:=n+1;
   begin if not exists(select 1 from public.memberships where workspace_id=i.workspace_id and user_id=i.actor and role in('admin','recruiter'))then data:=jsonb_build_object('eligible',false,'reason','Issuing editor access removed');else data:=ecod_comms_private.source(i.workspace_id,i.candidate_id,i.template_id,i.context);end if;exception when raise_exception then data:=jsonb_build_object('eligible',false,'reason','Scoped source unavailable');end;
   if i.expires_at<=clock_timestamp()or data->'eligible'<>'true'::jsonb or data->>'head'is distinct from i.source_head then update ecod_comms_private.intents set status='Suppressed',reason=case when i.expires_at<=clock_timestamp()then'Intent expired'when data->'eligible'<>'true'::jsonb then data->>'reason'else'Reviewed source changed'end,updated_at=clock_timestamp()where id=i.id;suppressed:=suppressed+1;continue;end if;
   hour:=extract(hour from clock_timestamp()at time zone'UTC');
   if hour<(data->'preference'->>'startHour')::integer or hour>=(data->'preference'->>'endHour')::integer then update ecod_comms_private.intents set available_at=clock_timestamp()+interval'1 hour',reason='Waiting for permitted UTC contact window'where id=i.id;continue;end if;
   if(select count(*)from ecod_comms_private.intents where workspace_id=i.workspace_id and candidate_id=i.candidate_id and status='Test recorded'and updated_at>clock_timestamp()-interval'24 hours')>=policy.daily_limit then update ecod_comms_private.intents set available_at=clock_timestamp()+interval'1 hour',reason='Candidate daily test frequency limit'where id=i.id;continue;end if;
   outcome:=case when policy.outcome='permanent'then'test permanent failure'when policy.outcome='transient'and i.attempts=0 then'test transient failure'else'test recorded'end;
   insert into ecod_comms_private.attempts(workspace_id,candidate_id,intent_id,attempt,outcome,checksum)values(i.workspace_id,i.candidate_id,i.id,i.attempts+1,outcome,encode(sha256(convert_to(i.preview::text,'UTF8')),'hex'));
   update ecod_comms_private.intents set attempts=attempts+1,status=case when outcome='test recorded'then'Test recorded'when outcome='test permanent failure'or attempts+1>=3 then'Failed'else'Retrying'end,reason=outcome,available_at=clock_timestamp()+interval'1 minute'*power(2,i.attempts),updated_at=clock_timestamp()where id=i.id;
   if outcome='test recorded'then recorded:=recorded+1;elsif outcome='test permanent failure'or i.attempts+1>=3 then failed:=failed+1;end if;
  end loop;
  exit when n>=p_limit;
 end loop;exit when n>=p_limit;end loop;return jsonb_build_object('transport','test-only','examined',n,'testRecorded',recorded,'suppressed',suppressed,'failed',failed);
end$$;
create or replace function public.api_test_communications(p_action text default'context',p_candidate uuid default null,p_operation uuid default null,p_head text default null,p_payload jsonb default'{}',p_offset integer default 0)returns jsonb language sql security invoker set search_path=''as $$select ecod_comms_private.api(p_action,p_candidate,p_operation,p_head,p_payload,p_offset)$$;
create or replace function public.worker_run_test_communications(p_limit integer default 20)returns jsonb language sql security invoker set search_path=''as $$select ecod_comms_private.run(p_limit)$$;
revoke all on function ecod_comms_private.source(uuid,uuid,uuid,jsonb),ecod_comms_private.api(text,uuid,uuid,text,jsonb,integer),ecod_comms_private.run(integer),public.api_test_communications(text,uuid,uuid,text,jsonb,integer),public.worker_run_test_communications(integer)from public,anon,authenticated;
grant execute on function ecod_comms_private.api(text,uuid,uuid,text,jsonb,integer),public.api_test_communications(text,uuid,uuid,text,jsonb,integer)to authenticated;
do $$begin if exists(select 1 from pg_roles where rolname='service_role')then grant execute on function ecod_comms_private.run(integer),public.worker_run_test_communications(integer)to service_role;end if;end$$;
commit;
